name: Print Changed Files

on:
  push:
    branches:
      - main

jobs:
  print_changed_files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: ${{ github.event_name == 'pull_request' && 2 || 0 }}
      - name: Get changed files
        id: changed-files
        run: |
          if ${{ github.event_name == 'pull_request' }}; then
              git diff --name-status -r HEAD^1 HEAD > changed_files.txt
          else
              git diff --name-status ${{ github.event.before }} ${{ github.event.after }} > changed_files.txt
          fi
          echo "changed_files=changed_files.txt" >> $GITHUB_ENV
      - name: List changed files with actions
        run: |
          while read -r line; do
              action=$(echo $line | cut -d' ' -f1)
              file=$(echo $line | cut -d' ' -f2-)
              case $action in
                  A) echo "$file was added";;
                  M) echo "$file was modified";;
                  D) echo "$file was deleted";;
                  R) old_file=$(echo $file | cut -d$'\t' -f1)
                     new_file=$(echo $file | cut -d$'\t' -f2)
                     echo "$old_file was renamed to $new_file";;
                  R100) old_file=$(echo $file | cut -d$'\t' -f1)
                     new_file=$(echo $file | cut -d$'\t' -f2)
                     echo "$old_file was renamed/moved to $new_file";;
                  C) new_file=$(echo $file | cut -d$'\t' -f2)
                     echo "$new_file was copied";;
                  *) echo "Unknown action for file: $file";;
              esac
          done < ${{ env.changed_files }}
      - name: Simply print lines
        run: |
          while read -r line; do
              echo $line
          done < ${{ env.changed_files }}
