name: Backup

on:
  workflow_dispatch:
    inputs:
      backup_clone:
        type: choice
        description: "'backup_clone' flag"
        options:
          - 'true'
          - 'false'
        required: false
        default: 'false'

jobs:
  backup_source_control:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup clone flag
        run: |
          if [ -n "${{ inputs.backup_clone }}" ]; then
            echo "backup_clone=${{ inputs.backup_clone }}" >> $GITHUB_ENV
          else
            echo "backup_clone=${{ vars.backup_clone }}" >> $GITHUB_ENV
          fi
      # Sets 'backup_flag' to true/false, based on the commit head
      # Sets to false, only if commit head is not found in commit history, happens when a commit is reset
      - name: Set backup flag
        run: |
          from_commit="${{ github.event.before }}"
          to_commit="${{ github.event.after }}"
          commits_on_head="$(git rev-list HEAD)"
          backup_flag=false
          if [[ $commits_on_head =~ (^|[[:space:]])$from_commit($|[[:space:]]) ]] && \
             [[ $commits_on_head =~ (^|[[:space:]])$to_commit($|[[:space:]]) ]]
          then
              echo "Setting backup flag to true"
              backup_flag=true
          else
              echo "Either before commit [$from_commit] or after commit [$to_commit] is missing in HEAD"
              echo "Skipping backup"
          fi
          echo "backup_flag=$backup_flag" >> $GITHUB_ENV
      # Loads a python script to make a GET call to the '/clone' endpoint
      - name: Load clone script
        if: env.backup_flag == 'true' && env.backup_clone == 'true'
        run: |
          cat << 'EOF' > script.py
          import requests
          response = requests.get(url="${{ secrets.backup_url }}/clone",
                                  headers={"authorization": "Bearer ${{ secrets.backup_token }}",
                                           "content-location": "${{ github.repository }};${{ github.ref }}"})
          response.raise_for_status()
          EOF
      # Loads a python script to make a POST call to the '/backup' endpoint
      - name: Load backup script
        if: env.backup_flag == 'true' && env.backup_clone != 'true'
        run: |
          cat << 'EOF' > script.py
          import requests
          from pprint import pprint
          with open('changed_files.txt') as file:
              changed = file.readlines()
          payload = {"create": {}, "modify": {}, "remove": [], "download": []}
          for change in changed:
              parts = change.strip().split()
              action = parts[0]
              if action in ("A", "M"):
                  assert len(parts) == 2, "Invalid Entry"
                  filepath = parts[1]
                  try:
                      with open(filepath) as f:
                          payload["create"][filepath] = f.read()
                  except UnicodeDecodeError:
                      payload["download"].append(filepath)
              elif action in ("R", "R100"):
                  assert len(parts) == 3, "Invalid Entry"
                  payload["modify"][parts[1]] = parts[2]
              else:
                  assert len(parts) == 2, "Invalid Entry"
                  payload["remove"].append(parts[1])
          response = requests.post(url="${{ secrets.backup_url }}/backup",
                                   headers={"authorization": "Bearer ${{ secrets.backup_token }}",
                                            "content-location": "${{ github.repository }};${{ github.ref }}"},
                                   json=payload)
          response.raise_for_status()
          EOF
      # Gets all the changes in the repo, runs only when 'backup_clone' variable is either not set or set to 'false'
      - name: Get changes
        if: env.backup_flag == 'true' && env.backup_clone != 'true'
        run: |
          from_commit="${{ github.event.before }}"
          to_commit="${{ github.event.after }}"
          git diff --name-status "$from_commit" "$to_commit" > changed_files.txt
          echo "changed_files=changed_files.txt" >> $GITHUB_ENV
      - name: Initiate backup
        if: env.backup_flag == 'true'
        run: |
          python script.py
